---
title: "Distance Exploration"
author: "Quinton Neville"
date: "6/24/2019"
output: 
  github_document: default
  html_document: default
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
#Setting root directory
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Load Pacman for multiple package loads
if (!require("pacman")) install.packages(pacman)

#Need most updated dplyr if haven't already done this
#install.packages("dplyr") #need updated dplyr for sf objects

#Load all the good stuff
pacman::p_load(tidyverse, purrr, sf, mapview, ggmap,
               patchwork, osmdata, mapview, traveltime,
               iterators, doParallel, foreach, parallel,
               geosphere)

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
  cache = TRUE
)

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output for knitr
options(scipen = 999999)
```


```{r echo = FALSE}
#Define functions for OSM Use  
#Fairfax read OSM to output tibble (tidyr df)
osm_to_df <- function(key = "leisure", value = "playground", type = "point") {
#Read in playground data
read.df <- getbb("fairfax county", format_out = "polygon") %>%
  opq() %>%
  add_osm_feature(key = key, value = value) %>%
  osmdata_sf()
    
    if (type == "point" & !is.null(read.df$osm_points)) {
      
      lat.long.df <- do.call(rbind, st_geometry(read.df$osm_points)) %>% 
        as_tibble() %>% 
        setNames(c("longitude", "latitude")) %>%
        mutate(object_id = 1:nrow(.) %>% as.factor()) %>%
        dplyr::select(object_id, everything())
      
    } else if (type == "polygon" & !is.null(read.df$osm_polygons)) {
      
      poly.list <- do.call(rbind, st_geometry(read.df$osm_polygons)) %>%
        lapply(as.tibble)
      npolys    <- length(poly.list)
      
      lat.long.df <- tibble(
        object_id = 1:npolys %>% as.factor(),
        coord.df  = poly.list
        ) %>%
        unnest(coord.df) %>%
        rename(
        longitude = lon,
        latitude  = lat
        )
      
    } else if (type == "line" & !is.null(read.df$osm_lines)) {
      
      line.list <- do.call(list, st_geometry(read.df$osm_lines)) %>%
        lapply(., rbind) %>%
        lapply(., as.tibble)
      nlines    <- length(line.list)
      
      lat.long.df <- tibble(
        object_id = 1:nlines %>% as.factor(),
        coord.df  = line.list
        ) %>%
        unnest(coord.df) %>%
        rename(
        longitude = lon,
        latitude  = lat
        )
    } else {
      ifelse(is.null(read.df$osm_points), stop("key/value incorrect or object type is empty"), 
             ifelse(!(type %in% c("point", "polygon", "line")), stop("type is not point, polygon, or line"),
                    stop("object type is empty, try another")))
    }
  
  return(lat.long.df)
}

#Base Map Function
fairfax.gg <- function() {
fairfax.box <- getbb("fairfax county")
fairfax.boundary <- getbb("fairfax county", format_out = "polygon") %>%
  as.tibble() %>%
  rename(longitude = `V1`, latitude = `V2`)

#Grab the map info (many varieties)
fairfax.map <- get_map(location = fairfax.box, source="stamen", maptype="watercolor", crop = TRUE)

#ggmap and ggplot map and boundary
ff.map <- ggmap(fairfax.map) +
  geom_polygon(data = fairfax.boundary, aes(x = longitude, y = latitude), colour = "black", size = 1, alpha = 0.1) +
  labs(
    x = "Longitude",
    y = "Latitude"
  )
  return(ff.map)
}

#Point Visualization
osm_point_plot <- function(ff.map, obj, value) {
  if (!is.data.frame(obj)) stop("OSM object is not a data frame")
  if (!is.ggplot(ff.map))  stop("Baseline Fairfax map is not a ggplot")
  ff.map +
  geom_point(data = obj, aes(x = longitude, y = latitude),
             size = 0.1, colour = "red", alpha = 0.25) + 
  geom_density_2d(data = obj, aes(x = longitude, y = latitude),
                  colour = "purple", alpha = 0.5) +
  labs(title = sprintf("Fairfax County %s", value))
  }

#Polygon Plot
osm_poly_plot <- function(ff.map, obj, value) {
  if (!is.data.frame(obj)) stop("OSM object is not a data frame")
  if (!is.ggplot(ff.map))  stop("Baseline Fairfax map is not a ggplot")
  ff.map +
  geom_polygon(data = obj, aes(x = longitude, y = latitude, group = object_id), 
               colour = "red", fill = "maroon", alpha = 0.5, size = 0.2) +
  labs(title = sprintf("Fairfax County %s", value))
  }

#Line Plot
osm_line_plot <- function(ff.map, obj, value) {
  if (!is.data.frame(obj)) stop("OSM object is not a data frame")
  if (!is.ggplot(ff.map))  stop("Baseline Fairfax map is not a ggplot")
  ff.map +
  geom_path(data = obj, aes(x = longitude, y = latitude, group = object_id), 
               colour = "red", alpha = 0.5, size = 0.5) +
  labs(title = sprintf("Fairfax County %s", value))
  }

#File Path Generator (for OSM specifically)
osm_filepath_gen <- function(data.folder, file.type, key, value, type) {
  date <- Sys.Date() %>% as.character() %>% str_replace_all("-", "_")
  file.type <- "csv"
  data.folder <- "original/osm"
  file.path <- sprintf("./data/%s/%s_%s.%s", 
                     data.folder,
                     date, 
                     paste(key, value, type, sep = "_"),
                     file.type)
  return(file.path)
}
```  

##Read Data and Generate OSM Data
```{r message = FALSE, warning = FALSE, results = FALSE, error = FALSE}
#Read
housing.df <- read_csv("./data/working/Fairfax_Housing_2018/fairfax_housing_2018_geo.csv") %>%
  janitor::clean_names() %>%
  mutate(
    housing_type = housing_type %>% as.factor(),
    water        = water %>% as.factor(),
    sewer        = sewer %>% as.factor(),
    gas          = gas   %>% as.factor(),
    district     = district  %>% as.factor(),
    highschool   = highschool %>% as.factor()
  )

#Generate OSM Point data (playground example)
playground.df <- osm_to_df()
```


##Load and Extract Relevant Geo Data from OSMR()

```{r message = FALSE, error = FALSE, warning = FALSE, include = FALSE, eval = FALSE, fig.height = 8, fig.width = 6}
#App-id and AppKey (request from travelTime platform)
app.id   <- "12251934"
app.key  <- "b5fb14aa79e0278e065d9de3ef95dbd9"
password <- "HIkrkq8DFN7SsTT7"

## Basic leaflet plotting
traveltime30 <- traveltime_map(appId      = app.id,
                               apiKey     = app.key,
                               location   = c(38.842669,-77.270272),
                               traveltime = 1800,
                               type       = "public_transport",
                               departure  = "2019-6-26T08:00:00Z")
mapview(traveltime30,  col.regions = c("grey")) + traveltime30

##Basic ggplot-ing
traveltimes <- c("walking", "cycling", "driving", "public_transport") %>%
  map(.x = ., ~ traveltime_map(appId      = app.id,
                         apiKey     = app.key,
                         location   = c(38.842669,-77.270272),
                         traveltime = 1800,
                         type       = .x,
                         departure  = "2019-6-26T08:00:00Z") %>%
        mutate(travel_mode = .x)
  )

#Bind into dataframe
travel.df <- do.call(rbind.data.frame, traveltimes) %>% as_tibble()

#GGplot
ff.map <- fairfax.gg()

ff.map +
  geom_sf(data = travel.df, inherit.aes = FALSE, aes(fill = travel_mode), alpha=0.5, color=NA) +
  scale_fill_viridis_d("Mode of Travel") +
  coord_sf(datum = NA)
```

##Write Function to Call <= 10 API TravelTimes/Minute  

```{r}
#Build function calculate one 
travel.time <- function(latitude    = 38.842669, 
                        longitude   = -77.270272, 
                        travel.mode = c("walking", "cycling", "driving", "public_transport"),
                        time        = 1200,
                        departure   = "2019-7-8T08:00:00Z") {
  #Grab travel df for each travel mode
      map(travel.mode, function(x) {
        travel.obj <- traveltime_map(appId    = app.id,
                                   apiKey     = app.key,
                                   location   = c(latitude, longitude),
                                   traveltime = time,
                                   type       = x,
                                   departure  = departure) %>%
        mutate(travel_mode = x)
        Sys.sleep(6)
        return(travel.obj)
        }) %>%
        do.call(rbind.data.frame, .) %>%
        as_tibble()
}


func <- function(x) {traveltime_map(appId      = app.id,
                                   apiKey     = app.key,
                                   location   = c(latitude, longitude),
                                   traveltime = time,
                                   type       = x,
                                   departure  = departure) %>%
        mutate(travel_mode = x)
        Sys.sleep(6)
}

func("walking")

map.var.time <- function(osm.df,                        
                        travel.mode = c("walking", "cycling", "driving", "public_transport"),
                        time        = 1200,
                        departure   = "2019-6-26T08:00:00Z") {
  osm.df %>%
    mutate(
      travel_sf = map2(.x = latitude, .y = longitude, ~ travel.time(latitude    = .x, 
                                                                    longtitude  = .y,
                                                                    travel.mode = travel.mode,
                                                                    time        = time,
                                                                    departure   = departure))  
    )
}


iterative.grid <- expand.grid()


#Test Function 1
a <- Sys.time()
travel.time(travel.mode = c("walking", "driving"))
b <- Sys.time()
b - a


#geosphere for centroid(x), x ~ two column long, lat matrix
```



