---
title: "Pre-PCA"
author: "VH"
date: "7/3/2019"
output: 
  github_document: default
  html_document: default 
---
```{r}
library(tidyverse)
#Setting root directory
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
#Read in the ACS wide and ACS long (tidy) data
acs.df <- read_csv("/home/vh5dg/dspg19fairfax/data/working/ACS_joined_estimates/2019_07_08_acs_all_geography.csv")
#acs.tidy.df <- read_csv("/home/vh5dg/dspg19fairfax/data/working/ACS_joined_estimates/2019_06_24_acs_all_geography_tidy.csv")
```

```{r}

find_pct <- function(dt){
  # only one id_type
  dt <- dt[, -grep("moe",colnames(dt))]
  dt$SUM = rowSums( dt[ sapply(dt, is.numeric)] )
  dt.pct <- dt %>% 
    mutate_if(is.numeric, funs(round(.*100/SUM,2)))
  colnames(dt.pct) <- gsub("est","pct",colnames(dt.pct))
  dt.pct
}

```

PUBLIC ASSISTANCE INCOME (PAI)

```{r}
#1. Data Description  
acs.PAI.df <- acs.df %>% select("id_type","id",contains('pai')) 

#Dimension
PAI.dim  <- acs.PAI.df %>% select(ends_with("est")) %>% dim()

PAI.vars <- str_extract(names(acs.PAI.df), "(?<=no_pai|pai).*(?=_est)") %>% 
  na.omit() %>% 
  unique() %>%
  gsub("_","-",.)

#Missing data
miss.df <- tibble(
  Variable = names(acs.PAI.df),
  Count = acs.PAI.df %>% map_dbl(.x = ., ~is.na(.x) %>% sum()),
  Percentage = acs.PAI.df %>% map_dbl(.x = ., ~is.na(.x) %>% mean())) %>%
  mutate(
    Percentage = as.character(Percentage * 100) %>% str_c(., "%")
  )
```

```{r}
acs.PAI.tract = (acs.PAI.df %>% filter(id_type=="census_tract") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.PAI.tract %>%
  knitr::kable() 

PAI_tract <- acs.PAI.tract %>% select(id_type,id,pai_pct) 
```

```{r}
acs.PAI.highschool = (acs.PAI.df %>% filter(id_type=="highschool_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.PAI.highschool %>%
  knitr::kable() 

PAI_highschool <- acs.PAI.highschool %>% select(id_type,id,pai_pct) 
```

```{r}
acs.PAI.supervisor = (acs.PAI.df %>% filter(id_type=="supervisor_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.PAI.supervisor %>%
  knitr::kable() 

PAI_supervisor <- acs.PAI.supervisor %>% select(id_type,id,pai_pct) 
```
RECOMBINE PAI
```{r}
PAI_proportions = do.call("rbind", list(
  PAI_tract,
  PAI_highschool,
  PAI_supervisor))
```



SUPPLEMENTAL SECURITY INCOME (SSI)

```{r}
#1. Data Description  
acs.SSI.df <- acs.df %>% select("id_type","id",contains('ssi_')) 

#Dimension
SSI.dim  <- acs.SSI.df %>% select(ends_with("est")) %>% dim()

SSI.vars <- str_extract(names(acs.SSI.df), "(?<=no_ssi|ssi).*(?=_est)") %>% 
  na.omit() %>% 
  unique() %>%
  gsub("_","-",.)

#Missing data
miss.df <- tibble(
  Variable = names(acs.SSI.df),
  Count = acs.SSI.df %>% map_dbl(.x = ., ~is.na(.x) %>% sum()),
  Percentage = acs.SSI.df %>% map_dbl(.x = ., ~is.na(.x) %>% mean())) %>%
  mutate(
    Percentage = as.character(Percentage * 100) %>% str_c(., "%")
  )
```

```{r}
acs.SSI.tract = (acs.SSI.df %>% filter(id_type=="census_tract") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.SSI.tract %>%
  knitr::kable() 

SSI_tract <- acs.SSI.tract %>% select(id_type,id,ssi_pct) 

```

```{r}
acs.SSI.highschool = (acs.SSI.df %>% filter(id_type=="highschool_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.SSI.highschool %>%
  knitr::kable() 

SSI_highschool <- acs.SSI.highschool %>% select(id_type,id,ssi_pct) 

```

```{r}
acs.SSI.supervisor = (acs.SSI.df %>% filter(id_type=="supervisor_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.SSI.supervisor %>%
  knitr::kable() 

SSI_supervisor <- acs.SSI.supervisor %>% select(id_type,id,ssi_pct) 
```

RECOMBINE SSI
```{r}
SSI_proportions = do.call("rbind", list(
  SSI_tract,
  SSI_highschool,
  SSI_supervisor))
```



UNENROLLED IN SCHOOL 


```{r}
#1. Data Description  
acs.unschool.df <- acs.df %>% select("id_type","id",contains('enrolled')) 

#Dimension
unschool.dim  <- acs.unschool.df %>% select(ends_with("est")) %>% dim()

unschool.vars <- str_extract(names(acs.unschool.df), "(?<=unenrolled|enrolled).*(?=_est)") %>% 
  na.omit() %>% 
  unique() %>%
  gsub("_","-",.)

#Missing data
miss.df <- tibble(
  Variable = names(acs.unschool.df),
  Count = acs.unschool.df %>% map_dbl(.x = ., ~is.na(.x) %>% sum()),
  Percentage = acs.unschool.df %>% map_dbl(.x = ., ~is.na(.x) %>% mean())) %>%
  mutate(
    Percentage = as.character(Percentage * 100) %>% str_c(., "%")
  )
```

```{r}
acs.unschool.tract = (acs.unschool.df %>% filter(id_type=="census_tract") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.unschool.tract %>%
  knitr::kable() 

unschool_tract <- acs.unschool.tract %>% select(id_type,id,unenrolled_pct) 

```

```{r}
acs.unschool.highschool = (acs.unschool.df %>% filter(id_type=="highschool_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.unschool.highschool %>%
  knitr::kable() 

unschool_highschool <- acs.unschool.highschool %>% select(id_type,id,unenrolled_pct) 

```

```{r}
acs.unschool.supervisor = (acs.unschool.df %>% filter(id_type=="supervisor_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.unschool.supervisor %>%
  knitr::kable() 

unschool_supervisor <- acs.unschool.supervisor %>% select(id_type,id,unenrolled_pct) 

```

RECOMBINE UNENROLED
```{r}
unenrolled_proportions = do.call("rbind", list(
  unschool_tract,
  unschool_highschool,
  unschool_supervisor))
```

POVERTY

```{r}
#1. Data Description  
acs.poverty.df <- acs.df %>% select("id_type","id",contains('poverty')) 

#Dimension
poverty.dim  <- acs.poverty.df %>% select(ends_with("est")) %>% dim()

poverty.vars <- str_extract(names(acs.poverty.df), "(?<=nonpoverty|poverty).*(?=_est)") %>% 
  na.omit() %>% 
  unique() %>%
  gsub("_","-",.)

#Missing data
miss.df <- tibble(
  Variable = names(acs.poverty.df),
  Count = acs.poverty.df %>% map_dbl(.x = ., ~is.na(.x) %>% sum()),
  Percentage = acs.poverty.df %>% map_dbl(.x = ., ~is.na(.x) %>% mean())) %>%
  mutate(
    Percentage = as.character(Percentage * 100) %>% str_c(., "%")
  )
```

```{r}
acs.poverty.tract = (acs.poverty.df %>% filter(id_type=="census_tract") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.poverty.tract %>%
  knitr::kable() 

poverty_tract <- acs.poverty.tract %>% select(id_type,id,poverty_pct) 

```

```{r}
acs.poverty.highschool = (acs.poverty.df %>% filter(id_type=="highschool_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.poverty.highschool %>%
  knitr::kable() 

poverty_highschool <- acs.poverty.highschool %>% select(id_type,id,poverty_pct) 

```

```{r}
acs.poverty.supervisor = (acs.poverty.df %>% filter(id_type=="supervisor_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.poverty.supervisor %>%
  knitr::kable() 

poverty_supervisor <- acs.poverty.supervisor %>% select(id_type,id,poverty_pct) 

```

RECOMBINE POVERTY
```{r}
poverty_proportions = do.call("rbind", list(
  poverty_tract,
  poverty_highschool,
  poverty_supervisor))
```



HEALTH INSURANCE COVERAGE

```{r}
#1. Data Description  
acs.HICOV.df <- acs.df %>% select("id_type","id",contains('hicov')) 

#Dimension
HICOV.dim  <- acs.HICOV.df %>% select(ends_with("est")) %>% dim()

HICOV.vars <- str_extract(names(acs.HICOV.df), "(?<=nohicov|hicov).*(?=_est)") %>% 
  na.omit() %>% 
  unique() %>%
  gsub("_","-",.)

#Missing data
miss.df <- tibble(
  Variable = names(acs.HICOV.df),
  Count = acs.HICOV.df %>% map_dbl(.x = ., ~is.na(.x) %>% sum()),
  Percentage = acs.HICOV.df %>% map_dbl(.x = ., ~is.na(.x) %>% mean())) %>%
  mutate(
    Percentage = as.character(Percentage * 100) %>% str_c(., "%")
  )
```

```{r}
acs.HICOV.tract = (acs.HICOV.df %>% filter(id_type=="census_tract") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.HICOV.tract %>%
  knitr::kable() 

HICOV_tract <- acs.HICOV.tract %>% select(id_type,id,no_hicov_pct) 

```

```{r}
acs.HICOV.highschool = (acs.HICOV.df %>% filter(id_type=="highschool_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.HICOV.highschool %>%
  knitr::kable() 

HICOV_highschool <- acs.HICOV.highschool %>% select(id_type,id,no_hicov_pct) 

```

```{r}
acs.HICOV.supervisor = (acs.HICOV.df %>% filter(id_type=="supervisor_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 
  
acs.HICOV.supervisor %>%
  knitr::kable() 

HICOV_supervisor <- acs.HICOV.supervisor %>% select(id_type,id,no_hicov_pct) 

```

RECOMBINE HICOV
```{r}
HICOV_proportions = do.call("rbind", list(
  HICOV_tract,
  HICOV_highschool,
  HICOV_supervisor))
```




COMMUTE TIME 

```{r}
#1. Data Description  
acs.Commute.df <- acs.df %>% select("id_type","id",contains('min')) 

#Dimension
Commute.dim  <- acs.Commute.df %>% select(ends_with("est")) %>% dim()

Commute.vars <- str_extract(names(acs.Commute.df), "(?<=min).*(?=_est)") %>% 
  na.omit() %>% 
  unique() %>%
  gsub("_","-",.)

#Missing data
miss.df <- tibble(
  Variable = names(acs.Commute.df),
  Count = acs.Commute.df %>% map_dbl(.x = ., ~is.na(.x) %>% sum()),
  Percentage = acs.Commute.df %>% map_dbl(.x = ., ~is.na(.x) %>% mean())) %>%
  mutate(
    Percentage = as.character(Percentage * 100) %>% str_c(., "%")
  )

#Adding moe to the new df. The function below requires it. 
acs.Commute.df$over_30min_commute_est<- (acs.Commute.df$min_30to60_est + acs.Commute.df$min_60to90_est + acs.Commute.df$min_over90_est)
acs.Commute.df$over_30min_commute_moe<- (acs.Commute.df$min_30to60_moe + acs.Commute.df$min_60to90_moe + acs.Commute.df$min_over90_moe)


acs.Commute_adjusted.df = acs.Commute.df %>% select(id_type,id,min_under30_est,min_under30_moe, over_30min_commute_est,over_30min_commute_moe)

```

```{r}
acs_commute_tract = (acs.Commute_adjusted.df %>% filter(id_type=="census_tract") %>%
  find_pct()  %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 

acs_commute_tract %>%
knitr::kable()

 
commute_tract <- acs_commute_tract %>% select(id_type,id,over_30min_commute_pct) 
```

```{r}
acs_commute_highschool = (acs.Commute_adjusted.df %>% filter(id_type=="highschool_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 

acs_commute_highschool %>%
knitr::kable() 

commute_highschool <- acs_commute_highschool %>% select(id_type,id,over_30min_commute_pct) 

```

```{r}
acs_commute_supervisor = (acs.Commute_adjusted.df %>% filter(id_type=="supervisor_district") %>%
  find_pct() %>%
  mutate_if(is.numeric, funs(as.character() %>% str_c(., "")))) 

acs_commute_supervisor %>%
knitr::kable() 

commute_supervisor <- acs_commute_supervisor %>% select(id_type,id,over_30min_commute_pct) 
```

RECOMBINE COMMUTE
```{r}
commute_proportions = do.call("rbind", list(
  commute_tract,
  commute_highschool,
  commute_supervisor))
```



FINAL MASTER CV
```{r}


master_census_dataset = (Reduce(function(x, y) merge(x, y, all=TRUE),list(PAI_proportions, SSI_proportions, unenrolled_proportions, poverty_proportions, HICOV_proportions, commute_proportions))) 
  



master_census_dataset = bind_cols(master_census_dataset %>%
                                    select(c(id, id_type)),
                                  master_census_dataset %>%
                                    select(-c(id,id_type)) %>% 
                                    map_df(., as.numeric))


#write.csv(master_census_dataset, "./data/working/ACS_final_index/master_census_dataset.csv")
```




