---
title: "Eliza ACS Exploration"
author: "Eliza"
date: "7/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LOAD PACKAGES AND LIBRARIES 
```{r setup, message = FALSE, warning = FALSE}
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

##install.packages("dplyr") # new  version
##install.packages(c("snakecase", "janitor")) #tidy names
##install.packages("pillar") #Dependency for patchwork
##devtools::install_github("thomasp85/patchwork") #For multi-panel plots
##install.packages(c("osmdata", "ggmap"))
##install.packages(c("sp", "sf"))

library(tidyverse) 
library(janitor)   #Clean names
##library(patchwork) #Multi panel plots
library(osmdata)   #OSM
library(ggmap)     #Tidy gg maps
library(purrr)     #Map functions
library(sp)        #Spatial forms
library(sf)        #Spatial forms
```

# DEFINE GEOGRAPHY TYPES
```{r}
#Define geography types (name of folder in ACS_etimates)
geo.types <- c("blockgroup", "district", "highschool", "opportunity")

#Function to read in each folder of .csv data (by variable est.)
read_acs <- function(geo.type = "blockgroup") {
  
#Check correct geo_type
  if (!(geo.type %in% geo.types)) {stop(sprintf("geo.type not one of: %s", str_c(geo.types, collapse = ", ")))}

#Generate path based on geography type
relative.path <- str_c("./data/working/ACS_estimates/", geo.type)
  
#List files, cast as tibble, map -> nest each data.csv, track data source
acs.file.df <- list.files(path = relative.path) %>%
  enframe() %>%
  rename(data_path = value) %>%
  mutate(
    data_path     = str_c(relative.path, "/", data_path),
    input_files   = map(.x = data_path, ~read_csv(.x)),
    data_source   = str_split(data_path, "/") %>% 
                    map_chr(6) %>%
                    str_remove(".csv")
  ) %>%
  dplyr::select(-data_path)

#Iteratively join each df by GEOID
acs.df     <- acs.file.df$input_files[[1]]  #Pull first data frame

#Join by specific ID (given geo_type)

join.by <- ifelse(geo.type %in% "blockgroup", "GEOID",
                  ifelse(geo.type %in% "district", "DISTRICT",
                         ifelse(geo.type %in% "highschool", "HIGHSCHOOL",
                                "TRACT")))

#Loop
for(i in 2:nrow(acs.file.df)) {
  acs.df <- left_join(acs.df, acs.file.df$input_files[[i]], by = join.by) 
}

#Clean names
acs.df <- acs.df %>%
  janitor::clean_names()

#Not Ideal but ID is always first column, cast factor
#acs.df[ ,1] <- as.factor(acs.df[ ,1])


#Profile Dim, missing ACS 
dim.acs <- dim(acs.df)
missing <- map_dbl(.x = acs.df, ~is.na(.x) %>% mean())
missing <- ifelse(any(missing != 0), "Missing Data Present", "No Missing Data")

#Return List of data, tidy data, dimension, and whether or not there is missing data
##Missing is a check to make sure the read operated correctly (as there is none)

  return(list(data = acs.df, dimension = dim.acs, missing = missing))
}

#Test and view output
##test <- read_acs()
##head(test$data)
##head(test$tidy_data)
##test$dimension  
##test$missing 
```

# Check that each read function works for each geography type
```{r}
blockgroup.list  <- read_acs("blockgroup")
district.list    <- read_acs("district")
highschool.list  <- read_acs("highschool")
opportunity.list <- read_acs("opportunity")
```

# Iterate and row_bind data together with Indicator for id and type of id (i.e. blockgroup, highschool, etc.)
```{r}
joined.df <- map_df(.x = geo.types, ~read_acs(.x)$data) %>%
                   mutate(
                     id_type = rep(geo.types, c(nrow(blockgroup.list$data),
                                           nrow(district.list$data), 
                                           nrow(highschool.list$data), 
                                           nrow(opportunity.list$data))) %>%
                                           as.factor() %>%
                        fct_recode(supervisor_district = "district",
                                   highschool_district = "highschool",
                                   census_tract = "opportunity"),
                     id = c(geoid, district, highschool, tract) %>%
                       na.omit()
                   ) %>%
                   dplyr::select(id, id_type, everything(), -c(geoid, district, tract, highschool))

joined.tidy.df <- joined.df %>% 
  gather(key = variable, value = value, -c(id, id_type))

#Function to write data with good filepath
write_acs <- function(data, geo.type = "blockgroup") {
  #Generate filepath
  file.path <- str_c(
    "./data/working/ACS_joined_estimates/",
    Sys.Date() %>%
      str_replace_all("-", "_"),
      str_c("_acs_", geo.type, ".csv")
  )
  #Write data with filepath
  write_csv(data, path = file.path)
}

#Write the regular and tidy (long) dataframes as csv's -- Only uncomment if you want to overwrite existing data
#write_acs(joined.df, "all_geography")
#write_acs(joined.tidy.df, "all_geography_tidy")
```

# READ IN ACS LONG/WIDE DATA
```{r}
acs.df <- read_csv("./data/working/ACS_joined_estimates/2019_06_24_acs_all_geography.csv")
acs.tidy.df <- read_csv("./data/working/ACS_joined_estimates/2019_06_24_acs_all_geography_tidy.csv")
```

# EXAMPLE PLOT 
```{r}
acs.df %>%
  mutate(
    id_type = fct_recode(id_type, 
                         Blockgroup = "blockgroup",
                         `Census Tract` = "census_tract",
                         `Highschool District` = "highschool_district",
                         `Supervisor District` = "supervisor_district"
                         ) 
  ) %>%
  dplyr::select(c(id_type, age0_5_est, age0_5_moe)) %>%
  ggplot(aes(x = age0_5_est, y = age0_5_moe, colour = id_type)) +
  geom_jitter(alpha = 0.32, size = 1, position = "jitter") +
  geom_smooth(method = "lm", se = FALSE, alpha = 0.8) +
  labs(
    x = "Estimated Number of Persons Aged 0-5",
    y = "Margin of Error",
    title = "Estimated Persons Aged 0-5 & M.O.E. by Geographic Boundary"
  ) +
  scale_colour_viridis_d("Geographic Type") + 
  guides(col = guide_legend(ncol = 2))
```

